### ISSUE TITLE
反应几个问题

### ISSUE THREAD

**Issue by KUYE-OLG** [xjq7/books#13]
AI、数据结构那里有很多失效的链接，如果作者方便的话麻烦更新一下喔。感谢作者大大

**Comment by xjq7** [comment]
> AI、数据结构那里有很多失效的链接，如果作者方便的话麻烦更新一下喔。感谢作者大大

因为百度云盘经常失效，现在正在一个个替换链接，你可以说下具体的哪基本书籍，我优先替换这些

**Comment by KUYE-OLG** [comment]
你好，您看是否可以使用阿里云或者蓝奏云的高速的网盘代替百度网盘呢？请稍等，稍后将书单发送至您的邮箱




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xjq7/books"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月11日(星期三) 中午12:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xjq7/books] 反应几个问题 (Issue #13)





  
AI、数据结构那里有很多失效的链接，如果作者方便的话麻烦更新一下喔。感谢作者大大
  
因为百度云盘经常失效，现在正在一个个替换链接，你可以说下具体的哪基本书籍，我优先替换这些

**Comment by KUYE-OLG** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xjq7/books"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月11日(星期三) 中午12:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xjq7/books] 反应几个问题 (Issue #13)





  
AI、数据结构那里有很多失效的链接，如果作者方便的话麻烦更新一下喔。感谢作者大大
  
因为百度云盘经常失效，现在正在一个个替换链接，你可以说下具体的哪基本书籍，我优先替换这些

**Comment by KUYE-OLG** [comment]
# 问题反馈

## 大数据链接全部失效 链接: https://pan.baidu.com/s/1pJlyfWmkgKbOO612W8iWYQ 提取码: x974

- 推荐系统实践
- Hadoop技术内幕
- Hadoop实战

## 深度学习

- 深度学习：智能时代的核心驱动力量,pdf,链接: https://pan.baidu.com/s/1zDoeK9-xhjrK_aATtH7igw 提取码: tvj2

## AI

- 智能信息融合与目标识别方法,pdf, 链接: https://pan.baidu.com/s/1KWJ2CCBYQBBHa1DshRVTYw 提取码: rfeh

- 机器智能：人工情感,pdf,链接: https://pan.baidu.com/s/1xlHoONqGechWyVs1zK-PEA 提取码: ft3f

- 无人机简史,pdf,链接: https://pan.baidu.com/s/1M8g1LMJb5b8kb1B3UzOVTw 提取码: eugd

- 人工智能技术,pdf,链接: https://pan.baidu.com/s/1LinMKa5_4xT9HHrWTwbp5A 提取码: 9kqk

**Comment by xjq7** [comment]
> 你好，您看是否可以使用阿里云或者蓝奏云的高速的网盘代替百度网盘呢？请稍等，稍后将书单发送至您的邮箱
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "xjq7/books" ***@***.***&gt;; 发送时间:&nbsp;2022年5月11日(星期三) 中午12:28 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [xjq7/books] 反应几个问题 (Issue #13) AI、数据结构那里有很多失效的链接，如果作者方便的话麻烦更新一下喔。感谢作者大大 因为百度云盘经常失效，现在正在一个个替换链接，你可以说下具体的哪基本书籍，我优先替换这些 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

会挂在服务器上，下载速度500k左右，对几十m书籍来说够用

**Comment by xjq7** [comment]
> * 人工智能技术

你列的都更新了

**Comment by xjq7** [comment]
> # 问题反馈
> ## 大数据链接全部失效 链接: https://pan.baidu.com/s/1pJlyfWmkgKbOO612W8iWYQ 提取码: x974
> * 推荐系统实践
> * Hadoop技术内幕
> * Hadoop实战
> 
> ## 深度学习
> * 深度学习：智能时代的核心驱动力量,pdf,链接: https://pan.baidu.com/s/1zDoeK9-xhjrK_aATtH7igw 提取码: tvj2
> 
> ## AI
> * 智能信息融合与目标识别方法,pdf, 链接: https://pan.baidu.com/s/1KWJ2CCBYQBBHa1DshRVTYw 提取码: rfeh
> * 机器智能：人工情感,pdf,链接: https://pan.baidu.com/s/1xlHoONqGechWyVs1zK-PEA 提取码: ft3f
> * 无人机简史,pdf,链接: https://pan.baidu.com/s/1M8g1LMJb5b8kb1B3UzOVTw 提取码: eugd
> * 人工智能技术,pdf,链接: https://pan.baidu.com/s/1LinMKa5_4xT9HHrWTwbp5A 提取码: 9kqk

你列的书单都更新了

**Comment by KUYE-OLG** [comment]
好的，谢谢
