### ISSUE TITLE
请问有没有《C#图解教程第5版》？

### ISSUE THREAD

**Issue by ScienceZone** [xjq7/books#2]
您好，有没有《C#图解教程》（第5版）的pdf版本？虽然买了纸质书，但不方便携带，还是没电子版的好。谢谢！

**Comment by SummerJoan3** [comment]
@ScienceZone 只找到第4版的,已添加

**Comment by 1300602123** [comment]
链接：https://pan.baidu.com/s/1abdYr83ybqJoc9HM9FOpLA 
提取码：xxyx

**Comment by wenthecook** [comment]
> 链接：https://pan.baidu.com/s/1abdYr83ybqJoc9HM9FOpLA
> 提取码：xxyx

感谢兄弟啊！这个又小又清晰！感谢！！！

**Comment by baihuziyou** [comment]
> 链接：https://pan.baidu.com/s/1abdYr83ybqJoc9HM9FOpLA 提取码：xxyx

老哥这个需要解压码

**Comment by zhangzdy** [comment]
感谢

**Comment by isPoto** [comment]
> 链接：https://pan.baidu.com/s/1abdYr83ybqJoc9HM9FOpLA 提取码：xxyx

感谢分享，已转存至 Zlibrary
https://book4you.org/book/19294370/b56b6e

**Comment by baihuziyou** [comment]
谢谢你😁



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月7日(周一) 凌晨3:52
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xjq7/books] 请问有没有《C#图解教程第5版》？ (#2)




  
链接：https://pan.baidu.com/s/1abdYr83ybqJoc9HM9FOpLA 提取码：xxyx
  
感谢分享，已转存至 Zlibrary
 https://book4you.org/book/19294370/b56b6e
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by djyddd** [comment]
> 链接：https://pan.baidu.com/s/1abdYr83ybqJoc9HM9FOpLA 提取码：xxyx

谢谢

**Comment by qingscan** [comment]
解压密码是多少

**Comment by xjq7** [comment]
@qingscan 评论区的链接有带解压密码

**Comment by wentianl20** [comment]
密码不对啊 password is wrong

**Comment by HaF-FD-LF** [comment]
> 链接：https://pan.baidu.com/s/1abdYr83ybqJoc9HM9FOpLA 提取码：xxyx

好人一生平安

**Comment by Leiber-CivilComEngineer** [comment]
https://github.com/Leiber-CivilComEngineer/Cshape_book_download/tree/main
我花了15rmb买的，免费分享给大家

**Comment by bigbosschenyibo** [comment]
good work
